version: 2
project_name: hyperstack-sdk-go
release:
  draft: true
  replace_existing_draft: true
  prerelease: auto
  github:
    owner: NexGenCloud
    name: hyperstack-sdk-go
  name_template: 'GO SDK Release {{ .Tag }}'
  
  header: |
    ## Welcome to the Release {{ .Tag }} of our Go SDK.
    Thank you for using our SDK. Below you'll find the changelog and assets for this release.
    
  footer: |
    ---
    We hope you enjoy using our SDK. Please report any issues on our GitHub page.

archives:
  - format: zip
    id: zip
    files:
      - 'lib/**'
      - LICENSE*
      - README*
      - CHANGELOG*
  - format: tar.gz
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    files:
      - 'lib/**'
      - LICENSE*
      - README*
      - CHANGELOG*

snapshot:
  name_template: '{{ .Version }}-SNAPSHOT-{{ .ShortCommit }}'

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

changelog:
  format: '{{ .SHA }}: {{ .Message }} ({{ .AuthorName }} <{{ .AuthorEmail }})'

dist: ./dist


#signs:
#  - id: default
#    cmd: gpg
#    args:
#      - --batch
#      - --yes
#      - --pinentry-mode
#      - loopback
#      - --passphrase
#      - '{{ .Env.GPG_PASSPHRASE }}'
#      - --local-user
#      - '{{ .Env.GPG_FINGERPRINT }}'
#      - --output
#      - '${signature}'
#      - --detach-sign
#      - '${artifact}'
#    signature: ${artifact}.sig
#    artifacts: checksum

before:
  hooks:
    - go mod tidy