/*
Infrahub-API

Leverage the Infrahub API and Hyperstack platform to easily create, manage, and scale powerful GPU virtual machines and their associated resources.   Access this SDK to automate the deployment of your workloads and streamline your infrastructure management.  To contribute, please raise an issue with a bug report, feature request, feedback, or general inquiry.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hyperstack

import (
	"encoding/json"
)

// checks if the OrganizationLevelBillingHistoryResponseAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganizationLevelBillingHistoryResponseAttributes{}

// OrganizationLevelBillingHistoryResponseAttributes struct for OrganizationLevelBillingHistoryResponseAttributes
type OrganizationLevelBillingHistoryResponseAttributes struct {
	Id *string `json:"id,omitempty"`
}

// NewOrganizationLevelBillingHistoryResponseAttributes instantiates a new OrganizationLevelBillingHistoryResponseAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationLevelBillingHistoryResponseAttributes() *OrganizationLevelBillingHistoryResponseAttributes {
	this := OrganizationLevelBillingHistoryResponseAttributes{}
	return &this
}

// NewOrganizationLevelBillingHistoryResponseAttributesWithDefaults instantiates a new OrganizationLevelBillingHistoryResponseAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationLevelBillingHistoryResponseAttributesWithDefaults() *OrganizationLevelBillingHistoryResponseAttributes {
	this := OrganizationLevelBillingHistoryResponseAttributes{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *OrganizationLevelBillingHistoryResponseAttributes) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationLevelBillingHistoryResponseAttributes) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *OrganizationLevelBillingHistoryResponseAttributes) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *OrganizationLevelBillingHistoryResponseAttributes) SetId(v string) {
	o.Id = &v
}

func (o OrganizationLevelBillingHistoryResponseAttributes) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganizationLevelBillingHistoryResponseAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableOrganizationLevelBillingHistoryResponseAttributes struct {
	value *OrganizationLevelBillingHistoryResponseAttributes
	isSet bool
}

func (v NullableOrganizationLevelBillingHistoryResponseAttributes) Get() *OrganizationLevelBillingHistoryResponseAttributes {
	return v.value
}

func (v *NullableOrganizationLevelBillingHistoryResponseAttributes) Set(val *OrganizationLevelBillingHistoryResponseAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationLevelBillingHistoryResponseAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationLevelBillingHistoryResponseAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationLevelBillingHistoryResponseAttributes(val *OrganizationLevelBillingHistoryResponseAttributes) *NullableOrganizationLevelBillingHistoryResponseAttributes {
	return &NullableOrganizationLevelBillingHistoryResponseAttributes{value: val, isSet: true}
}

func (v NullableOrganizationLevelBillingHistoryResponseAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationLevelBillingHistoryResponseAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
