/*
Infrahub-API

Leverage the Infrahub API and Hyperstack platform to easily create, manage, and scale powerful GPU virtual machines and their associated resources.   Access this SDK to automate the deployment of your workloads and streamline your infrastructure management.  To contribute, please raise an issue with a bug report, feature request, feedback, or general inquiry.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hyperstack

import (
	"encoding/json"
)

// checks if the GPUList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GPUList{}

// GPUList struct for GPUList
type GPUList struct {
	GpuList []GPUFields `json:"gpu_list,omitempty"`
	Message *string     `json:"message,omitempty"`
	Status  *bool       `json:"status,omitempty"`
}

// NewGPUList instantiates a new GPUList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGPUList() *GPUList {
	this := GPUList{}
	return &this
}

// NewGPUListWithDefaults instantiates a new GPUList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGPUListWithDefaults() *GPUList {
	this := GPUList{}
	return &this
}

// GetGpuList returns the GpuList field value if set, zero value otherwise.
func (o *GPUList) GetGpuList() []GPUFields {
	if o == nil || IsNil(o.GpuList) {
		var ret []GPUFields
		return ret
	}
	return o.GpuList
}

// GetGpuListOk returns a tuple with the GpuList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GPUList) GetGpuListOk() ([]GPUFields, bool) {
	if o == nil || IsNil(o.GpuList) {
		return nil, false
	}
	return o.GpuList, true
}

// HasGpuList returns a boolean if a field has been set.
func (o *GPUList) HasGpuList() bool {
	if o != nil && !IsNil(o.GpuList) {
		return true
	}

	return false
}

// SetGpuList gets a reference to the given []GPUFields and assigns it to the GpuList field.
func (o *GPUList) SetGpuList(v []GPUFields) {
	o.GpuList = v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *GPUList) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GPUList) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *GPUList) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *GPUList) SetMessage(v string) {
	o.Message = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GPUList) GetStatus() bool {
	if o == nil || IsNil(o.Status) {
		var ret bool
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GPUList) GetStatusOk() (*bool, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GPUList) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given bool and assigns it to the Status field.
func (o *GPUList) SetStatus(v bool) {
	o.Status = &v
}

func (o GPUList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GPUList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.GpuList) {
		toSerialize["gpu_list"] = o.GpuList
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableGPUList struct {
	value *GPUList
	isSet bool
}

func (v NullableGPUList) Get() *GPUList {
	return v.value
}

func (v *NullableGPUList) Set(val *GPUList) {
	v.value = val
	v.isSet = true
}

func (v NullableGPUList) IsSet() bool {
	return v.isSet
}

func (v *NullableGPUList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGPUList(val *GPUList) *NullableGPUList {
	return &NullableGPUList{value: val, isSet: true}
}

func (v NullableGPUList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGPUList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
