/*
Infrahub-API

Leverage the Infrahub API and Hyperstack platform to easily create, manage, and scale powerful GPU virtual machines and their associated resources.   Access this SDK to automate the deployment of your workloads and streamline your infrastructure management.  To contribute, please raise an issue with a bug report, feature request, feedback, or general inquiry.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hyperstack

import (
	"encoding/json"
)

// checks if the BillingHistory type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BillingHistory{}

// BillingHistory struct for BillingHistory
type BillingHistory struct {
	Attributes *Attributes            `json:"attributes,omitempty"`
	Metrics    map[string]interface{} `json:"metrics,omitempty"`
}

// NewBillingHistory instantiates a new BillingHistory object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBillingHistory() *BillingHistory {
	this := BillingHistory{}
	return &this
}

// NewBillingHistoryWithDefaults instantiates a new BillingHistory object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBillingHistoryWithDefaults() *BillingHistory {
	this := BillingHistory{}
	return &this
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *BillingHistory) GetAttributes() Attributes {
	if o == nil || IsNil(o.Attributes) {
		var ret Attributes
		return ret
	}
	return *o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingHistory) GetAttributesOk() (*Attributes, bool) {
	if o == nil || IsNil(o.Attributes) {
		return nil, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *BillingHistory) HasAttributes() bool {
	if o != nil && !IsNil(o.Attributes) {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given Attributes and assigns it to the Attributes field.
func (o *BillingHistory) SetAttributes(v Attributes) {
	o.Attributes = &v
}

// GetMetrics returns the Metrics field value if set, zero value otherwise.
func (o *BillingHistory) GetMetrics() map[string]interface{} {
	if o == nil || IsNil(o.Metrics) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metrics
}

// GetMetricsOk returns a tuple with the Metrics field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingHistory) GetMetricsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metrics) {
		return map[string]interface{}{}, false
	}
	return o.Metrics, true
}

// HasMetrics returns a boolean if a field has been set.
func (o *BillingHistory) HasMetrics() bool {
	if o != nil && !IsNil(o.Metrics) {
		return true
	}

	return false
}

// SetMetrics gets a reference to the given map[string]interface{} and assigns it to the Metrics field.
func (o *BillingHistory) SetMetrics(v map[string]interface{}) {
	o.Metrics = v
}

func (o BillingHistory) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BillingHistory) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Attributes) {
		toSerialize["attributes"] = o.Attributes
	}
	if !IsNil(o.Metrics) {
		toSerialize["metrics"] = o.Metrics
	}
	return toSerialize, nil
}

type NullableBillingHistory struct {
	value *BillingHistory
	isSet bool
}

func (v NullableBillingHistory) Get() *BillingHistory {
	return v.value
}

func (v *NullableBillingHistory) Set(val *BillingHistory) {
	v.value = val
	v.isSet = true
}

func (v NullableBillingHistory) IsSet() bool {
	return v.isSet
}

func (v *NullableBillingHistory) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBillingHistory(val *BillingHistory) *NullableBillingHistory {
	return &NullableBillingHistory{value: val, isSet: true}
}

func (v NullableBillingHistory) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBillingHistory) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
