/*
Infrahub-API

Leverage the Infrahub API and Hyperstack platform to easily create, manage, and scale powerful GPU virtual machines and their associated resources.   Access this SDK to automate the deployment of your workloads and streamline your infrastructure management.  To contribute, please raise an issue with a bug report, feature request, feedback, or general inquiry.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hyperstack

import (
	"encoding/json"
)

// checks if the ResourceLevelBucketBillingDetailsResponseModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResourceLevelBucketBillingDetailsResponseModel{}

// ResourceLevelBucketBillingDetailsResponseModel struct for ResourceLevelBucketBillingDetailsResponseModel
type ResourceLevelBucketBillingDetailsResponseModel struct {
	BillingHistoryBucketDetails *ResourceLevelBillingBucketDetailsResources `json:"billing_history_bucket_details,omitempty"`
	Message                     *string                                     `json:"message,omitempty"`
	Status                      *bool                                       `json:"status,omitempty"`
}

// NewResourceLevelBucketBillingDetailsResponseModel instantiates a new ResourceLevelBucketBillingDetailsResponseModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResourceLevelBucketBillingDetailsResponseModel() *ResourceLevelBucketBillingDetailsResponseModel {
	this := ResourceLevelBucketBillingDetailsResponseModel{}
	return &this
}

// NewResourceLevelBucketBillingDetailsResponseModelWithDefaults instantiates a new ResourceLevelBucketBillingDetailsResponseModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResourceLevelBucketBillingDetailsResponseModelWithDefaults() *ResourceLevelBucketBillingDetailsResponseModel {
	this := ResourceLevelBucketBillingDetailsResponseModel{}
	return &this
}

// GetBillingHistoryBucketDetails returns the BillingHistoryBucketDetails field value if set, zero value otherwise.
func (o *ResourceLevelBucketBillingDetailsResponseModel) GetBillingHistoryBucketDetails() ResourceLevelBillingBucketDetailsResources {
	if o == nil || IsNil(o.BillingHistoryBucketDetails) {
		var ret ResourceLevelBillingBucketDetailsResources
		return ret
	}
	return *o.BillingHistoryBucketDetails
}

// GetBillingHistoryBucketDetailsOk returns a tuple with the BillingHistoryBucketDetails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceLevelBucketBillingDetailsResponseModel) GetBillingHistoryBucketDetailsOk() (*ResourceLevelBillingBucketDetailsResources, bool) {
	if o == nil || IsNil(o.BillingHistoryBucketDetails) {
		return nil, false
	}
	return o.BillingHistoryBucketDetails, true
}

// HasBillingHistoryBucketDetails returns a boolean if a field has been set.
func (o *ResourceLevelBucketBillingDetailsResponseModel) HasBillingHistoryBucketDetails() bool {
	if o != nil && !IsNil(o.BillingHistoryBucketDetails) {
		return true
	}

	return false
}

// SetBillingHistoryBucketDetails gets a reference to the given ResourceLevelBillingBucketDetailsResources and assigns it to the BillingHistoryBucketDetails field.
func (o *ResourceLevelBucketBillingDetailsResponseModel) SetBillingHistoryBucketDetails(v ResourceLevelBillingBucketDetailsResources) {
	o.BillingHistoryBucketDetails = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ResourceLevelBucketBillingDetailsResponseModel) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceLevelBucketBillingDetailsResponseModel) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ResourceLevelBucketBillingDetailsResponseModel) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ResourceLevelBucketBillingDetailsResponseModel) SetMessage(v string) {
	o.Message = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ResourceLevelBucketBillingDetailsResponseModel) GetStatus() bool {
	if o == nil || IsNil(o.Status) {
		var ret bool
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceLevelBucketBillingDetailsResponseModel) GetStatusOk() (*bool, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ResourceLevelBucketBillingDetailsResponseModel) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given bool and assigns it to the Status field.
func (o *ResourceLevelBucketBillingDetailsResponseModel) SetStatus(v bool) {
	o.Status = &v
}

func (o ResourceLevelBucketBillingDetailsResponseModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResourceLevelBucketBillingDetailsResponseModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BillingHistoryBucketDetails) {
		toSerialize["billing_history_bucket_details"] = o.BillingHistoryBucketDetails
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableResourceLevelBucketBillingDetailsResponseModel struct {
	value *ResourceLevelBucketBillingDetailsResponseModel
	isSet bool
}

func (v NullableResourceLevelBucketBillingDetailsResponseModel) Get() *ResourceLevelBucketBillingDetailsResponseModel {
	return v.value
}

func (v *NullableResourceLevelBucketBillingDetailsResponseModel) Set(val *ResourceLevelBucketBillingDetailsResponseModel) {
	v.value = val
	v.isSet = true
}

func (v NullableResourceLevelBucketBillingDetailsResponseModel) IsSet() bool {
	return v.isSet
}

func (v *NullableResourceLevelBucketBillingDetailsResponseModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourceLevelBucketBillingDetailsResponseModel(val *ResourceLevelBucketBillingDetailsResponseModel) *NullableResourceLevelBucketBillingDetailsResponseModel {
	return &NullableResourceLevelBucketBillingDetailsResponseModel{value: val, isSet: true}
}

func (v NullableResourceLevelBucketBillingDetailsResponseModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourceLevelBucketBillingDetailsResponseModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
