/*
Infrahub-API

Leverage the Infrahub API and Hyperstack platform to easily create, manage, and scale powerful GPU virtual machines and their associated resources.   Access this SDK to automate the deployment of your workloads and streamline your infrastructure management.  To contribute, please raise an issue with a bug report, feature request, feedback, or general inquiry.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hyperstack

import (
	"encoding/json"
)

// checks if the ResourceLevelBillingBucketDetailsResources type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResourceLevelBillingBucketDetailsResources{}

// ResourceLevelBillingBucketDetailsResources struct for ResourceLevelBillingBucketDetailsResources
type ResourceLevelBillingBucketDetailsResources struct {
	Attributes *ResourceLevelBillingDetailsAttributes `json:"attributes,omitempty"`
	Metrics    *ResourceLevelBillingDetailsMetrics    `json:"metrics,omitempty"`
}

// NewResourceLevelBillingBucketDetailsResources instantiates a new ResourceLevelBillingBucketDetailsResources object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResourceLevelBillingBucketDetailsResources() *ResourceLevelBillingBucketDetailsResources {
	this := ResourceLevelBillingBucketDetailsResources{}
	return &this
}

// NewResourceLevelBillingBucketDetailsResourcesWithDefaults instantiates a new ResourceLevelBillingBucketDetailsResources object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResourceLevelBillingBucketDetailsResourcesWithDefaults() *ResourceLevelBillingBucketDetailsResources {
	this := ResourceLevelBillingBucketDetailsResources{}
	return &this
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *ResourceLevelBillingBucketDetailsResources) GetAttributes() ResourceLevelBillingDetailsAttributes {
	if o == nil || IsNil(o.Attributes) {
		var ret ResourceLevelBillingDetailsAttributes
		return ret
	}
	return *o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceLevelBillingBucketDetailsResources) GetAttributesOk() (*ResourceLevelBillingDetailsAttributes, bool) {
	if o == nil || IsNil(o.Attributes) {
		return nil, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *ResourceLevelBillingBucketDetailsResources) HasAttributes() bool {
	if o != nil && !IsNil(o.Attributes) {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given ResourceLevelBillingDetailsAttributes and assigns it to the Attributes field.
func (o *ResourceLevelBillingBucketDetailsResources) SetAttributes(v ResourceLevelBillingDetailsAttributes) {
	o.Attributes = &v
}

// GetMetrics returns the Metrics field value if set, zero value otherwise.
func (o *ResourceLevelBillingBucketDetailsResources) GetMetrics() ResourceLevelBillingDetailsMetrics {
	if o == nil || IsNil(o.Metrics) {
		var ret ResourceLevelBillingDetailsMetrics
		return ret
	}
	return *o.Metrics
}

// GetMetricsOk returns a tuple with the Metrics field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceLevelBillingBucketDetailsResources) GetMetricsOk() (*ResourceLevelBillingDetailsMetrics, bool) {
	if o == nil || IsNil(o.Metrics) {
		return nil, false
	}
	return o.Metrics, true
}

// HasMetrics returns a boolean if a field has been set.
func (o *ResourceLevelBillingBucketDetailsResources) HasMetrics() bool {
	if o != nil && !IsNil(o.Metrics) {
		return true
	}

	return false
}

// SetMetrics gets a reference to the given ResourceLevelBillingDetailsMetrics and assigns it to the Metrics field.
func (o *ResourceLevelBillingBucketDetailsResources) SetMetrics(v ResourceLevelBillingDetailsMetrics) {
	o.Metrics = &v
}

func (o ResourceLevelBillingBucketDetailsResources) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResourceLevelBillingBucketDetailsResources) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Attributes) {
		toSerialize["attributes"] = o.Attributes
	}
	if !IsNil(o.Metrics) {
		toSerialize["metrics"] = o.Metrics
	}
	return toSerialize, nil
}

type NullableResourceLevelBillingBucketDetailsResources struct {
	value *ResourceLevelBillingBucketDetailsResources
	isSet bool
}

func (v NullableResourceLevelBillingBucketDetailsResources) Get() *ResourceLevelBillingBucketDetailsResources {
	return v.value
}

func (v *NullableResourceLevelBillingBucketDetailsResources) Set(val *ResourceLevelBillingBucketDetailsResources) {
	v.value = val
	v.isSet = true
}

func (v NullableResourceLevelBillingBucketDetailsResources) IsSet() bool {
	return v.isSet
}

func (v *NullableResourceLevelBillingBucketDetailsResources) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourceLevelBillingBucketDetailsResources(val *ResourceLevelBillingBucketDetailsResources) *NullableResourceLevelBillingBucketDetailsResources {
	return &NullableResourceLevelBillingBucketDetailsResources{value: val, isSet: true}
}

func (v NullableResourceLevelBillingBucketDetailsResources) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourceLevelBillingBucketDetailsResources) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
