/*
Infrahub-API

Leverage the Infrahub API and Hyperstack platform to easily create, manage, and scale powerful GPU virtual machines and their associated resources.   Access this SDK to automate the deployment of your workloads and streamline your infrastructure management.  To contribute, please raise an issue with a bug report, feature request, feedback, or general inquiry.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hyperstack

import (
	"encoding/json"
)

// checks if the GetCustomerContractsListResponseModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetCustomerContractsListResponseModel{}

// GetCustomerContractsListResponseModel struct for GetCustomerContractsListResponseModel
type GetCustomerContractsListResponseModel struct {
	Contracts []CustomerContractFields `json:"contracts,omitempty"`
	Count     *int32                   `json:"count,omitempty"`
	Message   *string                  `json:"message,omitempty"`
	Status    *bool                    `json:"status,omitempty"`
}

// NewGetCustomerContractsListResponseModel instantiates a new GetCustomerContractsListResponseModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetCustomerContractsListResponseModel() *GetCustomerContractsListResponseModel {
	this := GetCustomerContractsListResponseModel{}
	return &this
}

// NewGetCustomerContractsListResponseModelWithDefaults instantiates a new GetCustomerContractsListResponseModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetCustomerContractsListResponseModelWithDefaults() *GetCustomerContractsListResponseModel {
	this := GetCustomerContractsListResponseModel{}
	return &this
}

// GetContracts returns the Contracts field value if set, zero value otherwise.
func (o *GetCustomerContractsListResponseModel) GetContracts() []CustomerContractFields {
	if o == nil || IsNil(o.Contracts) {
		var ret []CustomerContractFields
		return ret
	}
	return o.Contracts
}

// GetContractsOk returns a tuple with the Contracts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCustomerContractsListResponseModel) GetContractsOk() ([]CustomerContractFields, bool) {
	if o == nil || IsNil(o.Contracts) {
		return nil, false
	}
	return o.Contracts, true
}

// HasContracts returns a boolean if a field has been set.
func (o *GetCustomerContractsListResponseModel) HasContracts() bool {
	if o != nil && !IsNil(o.Contracts) {
		return true
	}

	return false
}

// SetContracts gets a reference to the given []CustomerContractFields and assigns it to the Contracts field.
func (o *GetCustomerContractsListResponseModel) SetContracts(v []CustomerContractFields) {
	o.Contracts = v
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *GetCustomerContractsListResponseModel) GetCount() int32 {
	if o == nil || IsNil(o.Count) {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCustomerContractsListResponseModel) GetCountOk() (*int32, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *GetCustomerContractsListResponseModel) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *GetCustomerContractsListResponseModel) SetCount(v int32) {
	o.Count = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *GetCustomerContractsListResponseModel) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCustomerContractsListResponseModel) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *GetCustomerContractsListResponseModel) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *GetCustomerContractsListResponseModel) SetMessage(v string) {
	o.Message = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetCustomerContractsListResponseModel) GetStatus() bool {
	if o == nil || IsNil(o.Status) {
		var ret bool
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCustomerContractsListResponseModel) GetStatusOk() (*bool, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetCustomerContractsListResponseModel) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given bool and assigns it to the Status field.
func (o *GetCustomerContractsListResponseModel) SetStatus(v bool) {
	o.Status = &v
}

func (o GetCustomerContractsListResponseModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetCustomerContractsListResponseModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Contracts) {
		toSerialize["contracts"] = o.Contracts
	}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableGetCustomerContractsListResponseModel struct {
	value *GetCustomerContractsListResponseModel
	isSet bool
}

func (v NullableGetCustomerContractsListResponseModel) Get() *GetCustomerContractsListResponseModel {
	return v.value
}

func (v *NullableGetCustomerContractsListResponseModel) Set(val *GetCustomerContractsListResponseModel) {
	v.value = val
	v.isSet = true
}

func (v NullableGetCustomerContractsListResponseModel) IsSet() bool {
	return v.isSet
}

func (v *NullableGetCustomerContractsListResponseModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetCustomerContractsListResponseModel(val *GetCustomerContractsListResponseModel) *NullableGetCustomerContractsListResponseModel {
	return &NullableGetCustomerContractsListResponseModel{value: val, isSet: true}
}

func (v NullableGetCustomerContractsListResponseModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetCustomerContractsListResponseModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
