/*
Infrahub-API

Leverage the Infrahub API and Hyperstack platform to easily create, manage, and scale powerful GPU virtual machines and their associated resources.   Access this SDK to automate the deployment of your workloads and streamline your infrastructure management.  To contribute, please raise an issue with a bug report, feature request, feedback, or general inquiry.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hyperstack

import (
	"encoding/json"
)

// checks if the ResourceBillingResponseForCustomer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResourceBillingResponseForCustomer{}

// ResourceBillingResponseForCustomer struct for ResourceBillingResponseForCustomer
type ResourceBillingResponseForCustomer struct {
	CalculatedResourceBills *ResourceObjectResponseForCustomer `json:"calculated_resource_bills,omitempty"`
	Message                 *string                            `json:"message,omitempty"`
	Status                  *bool                              `json:"status,omitempty"`
}

// NewResourceBillingResponseForCustomer instantiates a new ResourceBillingResponseForCustomer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResourceBillingResponseForCustomer() *ResourceBillingResponseForCustomer {
	this := ResourceBillingResponseForCustomer{}
	return &this
}

// NewResourceBillingResponseForCustomerWithDefaults instantiates a new ResourceBillingResponseForCustomer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResourceBillingResponseForCustomerWithDefaults() *ResourceBillingResponseForCustomer {
	this := ResourceBillingResponseForCustomer{}
	return &this
}

// GetCalculatedResourceBills returns the CalculatedResourceBills field value if set, zero value otherwise.
func (o *ResourceBillingResponseForCustomer) GetCalculatedResourceBills() ResourceObjectResponseForCustomer {
	if o == nil || IsNil(o.CalculatedResourceBills) {
		var ret ResourceObjectResponseForCustomer
		return ret
	}
	return *o.CalculatedResourceBills
}

// GetCalculatedResourceBillsOk returns a tuple with the CalculatedResourceBills field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceBillingResponseForCustomer) GetCalculatedResourceBillsOk() (*ResourceObjectResponseForCustomer, bool) {
	if o == nil || IsNil(o.CalculatedResourceBills) {
		return nil, false
	}
	return o.CalculatedResourceBills, true
}

// HasCalculatedResourceBills returns a boolean if a field has been set.
func (o *ResourceBillingResponseForCustomer) HasCalculatedResourceBills() bool {
	if o != nil && !IsNil(o.CalculatedResourceBills) {
		return true
	}

	return false
}

// SetCalculatedResourceBills gets a reference to the given ResourceObjectResponseForCustomer and assigns it to the CalculatedResourceBills field.
func (o *ResourceBillingResponseForCustomer) SetCalculatedResourceBills(v ResourceObjectResponseForCustomer) {
	o.CalculatedResourceBills = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ResourceBillingResponseForCustomer) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceBillingResponseForCustomer) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ResourceBillingResponseForCustomer) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ResourceBillingResponseForCustomer) SetMessage(v string) {
	o.Message = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ResourceBillingResponseForCustomer) GetStatus() bool {
	if o == nil || IsNil(o.Status) {
		var ret bool
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceBillingResponseForCustomer) GetStatusOk() (*bool, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ResourceBillingResponseForCustomer) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given bool and assigns it to the Status field.
func (o *ResourceBillingResponseForCustomer) SetStatus(v bool) {
	o.Status = &v
}

func (o ResourceBillingResponseForCustomer) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResourceBillingResponseForCustomer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CalculatedResourceBills) {
		toSerialize["calculated_resource_bills"] = o.CalculatedResourceBills
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableResourceBillingResponseForCustomer struct {
	value *ResourceBillingResponseForCustomer
	isSet bool
}

func (v NullableResourceBillingResponseForCustomer) Get() *ResourceBillingResponseForCustomer {
	return v.value
}

func (v *NullableResourceBillingResponseForCustomer) Set(val *ResourceBillingResponseForCustomer) {
	v.value = val
	v.isSet = true
}

func (v NullableResourceBillingResponseForCustomer) IsSet() bool {
	return v.isSet
}

func (v *NullableResourceBillingResponseForCustomer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourceBillingResponseForCustomer(val *ResourceBillingResponseForCustomer) *NullableResourceBillingResponseForCustomer {
	return &NullableResourceBillingResponseForCustomer{value: val, isSet: true}
}

func (v NullableResourceBillingResponseForCustomer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourceBillingResponseForCustomer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
