/*
Infrahub-API

Leverage the Infrahub API and Hyperstack platform to easily create, manage, and scale powerful GPU virtual machines and their associated resources.   Access this SDK to automate the deployment of your workloads and streamline your infrastructure management.  To contribute, please raise an issue with a bug report, feature request, feedback, or general inquiry.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hyperstack

import (
	"encoding/json"
)

// checks if the SubResourcesGraphResponseModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubResourcesGraphResponseModel{}

// SubResourcesGraphResponseModel struct for SubResourcesGraphResponseModel
type SubResourcesGraphResponseModel struct {
	Message           *string                         `json:"message,omitempty"`
	Status            *bool                           `json:"status,omitempty"`
	SubResourcesCosts *SubResourcesCostsResponseModel `json:"sub_resources_costs,omitempty"`
}

// NewSubResourcesGraphResponseModel instantiates a new SubResourcesGraphResponseModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubResourcesGraphResponseModel() *SubResourcesGraphResponseModel {
	this := SubResourcesGraphResponseModel{}
	return &this
}

// NewSubResourcesGraphResponseModelWithDefaults instantiates a new SubResourcesGraphResponseModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubResourcesGraphResponseModelWithDefaults() *SubResourcesGraphResponseModel {
	this := SubResourcesGraphResponseModel{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *SubResourcesGraphResponseModel) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubResourcesGraphResponseModel) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *SubResourcesGraphResponseModel) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *SubResourcesGraphResponseModel) SetMessage(v string) {
	o.Message = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *SubResourcesGraphResponseModel) GetStatus() bool {
	if o == nil || IsNil(o.Status) {
		var ret bool
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubResourcesGraphResponseModel) GetStatusOk() (*bool, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *SubResourcesGraphResponseModel) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given bool and assigns it to the Status field.
func (o *SubResourcesGraphResponseModel) SetStatus(v bool) {
	o.Status = &v
}

// GetSubResourcesCosts returns the SubResourcesCosts field value if set, zero value otherwise.
func (o *SubResourcesGraphResponseModel) GetSubResourcesCosts() SubResourcesCostsResponseModel {
	if o == nil || IsNil(o.SubResourcesCosts) {
		var ret SubResourcesCostsResponseModel
		return ret
	}
	return *o.SubResourcesCosts
}

// GetSubResourcesCostsOk returns a tuple with the SubResourcesCosts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubResourcesGraphResponseModel) GetSubResourcesCostsOk() (*SubResourcesCostsResponseModel, bool) {
	if o == nil || IsNil(o.SubResourcesCosts) {
		return nil, false
	}
	return o.SubResourcesCosts, true
}

// HasSubResourcesCosts returns a boolean if a field has been set.
func (o *SubResourcesGraphResponseModel) HasSubResourcesCosts() bool {
	if o != nil && !IsNil(o.SubResourcesCosts) {
		return true
	}

	return false
}

// SetSubResourcesCosts gets a reference to the given SubResourcesCostsResponseModel and assigns it to the SubResourcesCosts field.
func (o *SubResourcesGraphResponseModel) SetSubResourcesCosts(v SubResourcesCostsResponseModel) {
	o.SubResourcesCosts = &v
}

func (o SubResourcesGraphResponseModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubResourcesGraphResponseModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.SubResourcesCosts) {
		toSerialize["sub_resources_costs"] = o.SubResourcesCosts
	}
	return toSerialize, nil
}

type NullableSubResourcesGraphResponseModel struct {
	value *SubResourcesGraphResponseModel
	isSet bool
}

func (v NullableSubResourcesGraphResponseModel) Get() *SubResourcesGraphResponseModel {
	return v.value
}

func (v *NullableSubResourcesGraphResponseModel) Set(val *SubResourcesGraphResponseModel) {
	v.value = val
	v.isSet = true
}

func (v NullableSubResourcesGraphResponseModel) IsSet() bool {
	return v.isSet
}

func (v *NullableSubResourcesGraphResponseModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubResourcesGraphResponseModel(val *SubResourcesGraphResponseModel) *NullableSubResourcesGraphResponseModel {
	return &NullableSubResourcesGraphResponseModel{value: val, isSet: true}
}

func (v NullableSubResourcesGraphResponseModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubResourcesGraphResponseModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
