/*
Infrahub-API

Leverage the Infrahub API and Hyperstack platform to easily create, manage, and scale powerful GPU virtual machines and their associated resources.   Access this SDK to automate the deployment of your workloads and streamline your infrastructure management.  To contribute, please raise an issue with a bug report, feature request, feedback, or general inquiry.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hyperstack

import (
	"encoding/json"
)

// checks if the FlavorLabelFields type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FlavorLabelFields{}

// FlavorLabelFields struct for FlavorLabelFields
type FlavorLabelFields struct {
	//
	Id *int32 `json:"id,omitempty"`
	//
	Label *string `json:"label,omitempty"`
}

// NewFlavorLabelFields instantiates a new FlavorLabelFields object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFlavorLabelFields() *FlavorLabelFields {
	this := FlavorLabelFields{}
	return &this
}

// NewFlavorLabelFieldsWithDefaults instantiates a new FlavorLabelFields object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFlavorLabelFieldsWithDefaults() *FlavorLabelFields {
	this := FlavorLabelFields{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *FlavorLabelFields) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlavorLabelFields) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *FlavorLabelFields) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *FlavorLabelFields) SetId(v int32) {
	o.Id = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *FlavorLabelFields) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlavorLabelFields) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *FlavorLabelFields) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *FlavorLabelFields) SetLabel(v string) {
	o.Label = &v
}

func (o FlavorLabelFields) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FlavorLabelFields) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	return toSerialize, nil
}

type NullableFlavorLabelFields struct {
	value *FlavorLabelFields
	isSet bool
}

func (v NullableFlavorLabelFields) Get() *FlavorLabelFields {
	return v.value
}

func (v *NullableFlavorLabelFields) Set(val *FlavorLabelFields) {
	v.value = val
	v.isSet = true
}

func (v NullableFlavorLabelFields) IsSet() bool {
	return v.isSet
}

func (v *NullableFlavorLabelFields) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFlavorLabelFields(val *FlavorLabelFields) *NullableFlavorLabelFields {
	return &NullableFlavorLabelFields{value: val, isSet: true}
}

func (v NullableFlavorLabelFields) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFlavorLabelFields) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
