/*
Infrahub-API

Leverage the Infrahub API and Hyperstack platform to easily create, manage, and scale powerful GPU virtual machines and their associated resources.   Access this SDK to automate the deployment of your workloads and streamline your infrastructure management.  To contribute, please raise an issue with a bug report, feature request, feedback, or general inquiry.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hyperstack

import (
	"encoding/json"
)

// checks if the MFAStatusResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MFAStatusResponse{}

// MFAStatusResponse struct for MFAStatusResponse
type MFAStatusResponse struct {
	Message *string          `json:"message,omitempty"`
	Mfa     *MFAStatusFields `json:"mfa,omitempty"`
	Status  *bool            `json:"status,omitempty"`
}

// NewMFAStatusResponse instantiates a new MFAStatusResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMFAStatusResponse() *MFAStatusResponse {
	this := MFAStatusResponse{}
	return &this
}

// NewMFAStatusResponseWithDefaults instantiates a new MFAStatusResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMFAStatusResponseWithDefaults() *MFAStatusResponse {
	this := MFAStatusResponse{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *MFAStatusResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MFAStatusResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *MFAStatusResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *MFAStatusResponse) SetMessage(v string) {
	o.Message = &v
}

// GetMfa returns the Mfa field value if set, zero value otherwise.
func (o *MFAStatusResponse) GetMfa() MFAStatusFields {
	if o == nil || IsNil(o.Mfa) {
		var ret MFAStatusFields
		return ret
	}
	return *o.Mfa
}

// GetMfaOk returns a tuple with the Mfa field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MFAStatusResponse) GetMfaOk() (*MFAStatusFields, bool) {
	if o == nil || IsNil(o.Mfa) {
		return nil, false
	}
	return o.Mfa, true
}

// HasMfa returns a boolean if a field has been set.
func (o *MFAStatusResponse) HasMfa() bool {
	if o != nil && !IsNil(o.Mfa) {
		return true
	}

	return false
}

// SetMfa gets a reference to the given MFAStatusFields and assigns it to the Mfa field.
func (o *MFAStatusResponse) SetMfa(v MFAStatusFields) {
	o.Mfa = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *MFAStatusResponse) GetStatus() bool {
	if o == nil || IsNil(o.Status) {
		var ret bool
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MFAStatusResponse) GetStatusOk() (*bool, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *MFAStatusResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given bool and assigns it to the Status field.
func (o *MFAStatusResponse) SetStatus(v bool) {
	o.Status = &v
}

func (o MFAStatusResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MFAStatusResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Mfa) {
		toSerialize["mfa"] = o.Mfa
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableMFAStatusResponse struct {
	value *MFAStatusResponse
	isSet bool
}

func (v NullableMFAStatusResponse) Get() *MFAStatusResponse {
	return v.value
}

func (v *NullableMFAStatusResponse) Set(val *MFAStatusResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMFAStatusResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMFAStatusResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMFAStatusResponse(val *MFAStatusResponse) *NullableMFAStatusResponse {
	return &NullableMFAStatusResponse{value: val, isSet: true}
}

func (v NullableMFAStatusResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMFAStatusResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
