/*
Infrahub-API

Leverage the Infrahub API and Hyperstack platform to easily create, manage, and scale powerful GPU virtual machines and their associated resources.   Access this SDK to automate the deployment of your workloads and streamline your infrastructure management.  To contribute, please raise an issue with a bug report, feature request, feedback, or general inquiry.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hyperstack

import (
	"encoding/json"
)

// checks if the LableResonse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LableResonse{}

// LableResonse struct for LableResonse
type LableResonse struct {
	Id    *int32  `json:"id,omitempty"`
	Label *string `json:"label,omitempty"`
}

// NewLableResonse instantiates a new LableResonse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLableResonse() *LableResonse {
	this := LableResonse{}
	return &this
}

// NewLableResonseWithDefaults instantiates a new LableResonse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLableResonseWithDefaults() *LableResonse {
	this := LableResonse{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *LableResonse) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LableResonse) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *LableResonse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *LableResonse) SetId(v int32) {
	o.Id = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *LableResonse) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LableResonse) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *LableResonse) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *LableResonse) SetLabel(v string) {
	o.Label = &v
}

func (o LableResonse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LableResonse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	return toSerialize, nil
}

type NullableLableResonse struct {
	value *LableResonse
	isSet bool
}

func (v NullableLableResonse) Get() *LableResonse {
	return v.value
}

func (v *NullableLableResonse) Set(val *LableResonse) {
	v.value = val
	v.isSet = true
}

func (v NullableLableResonse) IsSet() bool {
	return v.isSet
}

func (v *NullableLableResonse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLableResonse(val *LableResonse) *NullableLableResonse {
	return &NullableLableResonse{value: val, isSet: true}
}

func (v NullableLableResonse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLableResonse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
