/*
Infrahub-API

Leverage the Infrahub API and Hyperstack platform to easily create, manage, and scale powerful GPU virtual machines and their associated resources.   Access this SDK to automate the deployment of your workloads and streamline your infrastructure management.  To contribute, please raise an issue with a bug report, feature request, feedback, or general inquiry.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hyperstack

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the UpdateDiscountsStatusPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateDiscountsStatusPayload{}

// UpdateDiscountsStatusPayload struct for UpdateDiscountsStatusPayload
type UpdateDiscountsStatusPayload struct {
	DiscountStatus string `json:"discount_status"`
}

type _UpdateDiscountsStatusPayload UpdateDiscountsStatusPayload

// NewUpdateDiscountsStatusPayload instantiates a new UpdateDiscountsStatusPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateDiscountsStatusPayload(discountStatus string) *UpdateDiscountsStatusPayload {
	this := UpdateDiscountsStatusPayload{}
	this.DiscountStatus = discountStatus
	return &this
}

// NewUpdateDiscountsStatusPayloadWithDefaults instantiates a new UpdateDiscountsStatusPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateDiscountsStatusPayloadWithDefaults() *UpdateDiscountsStatusPayload {
	this := UpdateDiscountsStatusPayload{}
	return &this
}

// GetDiscountStatus returns the DiscountStatus field value
func (o *UpdateDiscountsStatusPayload) GetDiscountStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DiscountStatus
}

// GetDiscountStatusOk returns a tuple with the DiscountStatus field value
// and a boolean to check if the value has been set.
func (o *UpdateDiscountsStatusPayload) GetDiscountStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DiscountStatus, true
}

// SetDiscountStatus sets field value
func (o *UpdateDiscountsStatusPayload) SetDiscountStatus(v string) {
	o.DiscountStatus = v
}

func (o UpdateDiscountsStatusPayload) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateDiscountsStatusPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["discount_status"] = o.DiscountStatus
	return toSerialize, nil
}

func (o *UpdateDiscountsStatusPayload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"discount_status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateDiscountsStatusPayload := _UpdateDiscountsStatusPayload{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateDiscountsStatusPayload)

	if err != nil {
		return err
	}

	*o = UpdateDiscountsStatusPayload(varUpdateDiscountsStatusPayload)

	return err
}

type NullableUpdateDiscountsStatusPayload struct {
	value *UpdateDiscountsStatusPayload
	isSet bool
}

func (v NullableUpdateDiscountsStatusPayload) Get() *UpdateDiscountsStatusPayload {
	return v.value
}

func (v *NullableUpdateDiscountsStatusPayload) Set(val *UpdateDiscountsStatusPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateDiscountsStatusPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateDiscountsStatusPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateDiscountsStatusPayload(val *UpdateDiscountsStatusPayload) *NullableUpdateDiscountsStatusPayload {
	return &NullableUpdateDiscountsStatusPayload{value: val, isSet: true}
}

func (v NullableUpdateDiscountsStatusPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateDiscountsStatusPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
