/*
Infrahub-API

Leverage the Infrahub API and Hyperstack platform to easily create, manage, and scale powerful GPU virtual machines and their associated resources.   Access this SDK to automate the deployment of your workloads and streamline your infrastructure management.  To contribute, please raise an issue with a bug report, feature request, feedback, or general inquiry.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hyperstack

import (
	"encoding/json"
)

// checks if the ResourceLevelClusterBillingHistoryResponseModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResourceLevelClusterBillingHistoryResponseModel{}

// ResourceLevelClusterBillingHistoryResponseModel struct for ResourceLevelClusterBillingHistoryResponseModel
type ResourceLevelClusterBillingHistoryResponseModel struct {
	BillingHistoryCluster *ResourceLevelBillingHistory `json:"billing_history_cluster,omitempty"`
	Message               *string                      `json:"message,omitempty"`
	Status                *bool                        `json:"status,omitempty"`
}

// NewResourceLevelClusterBillingHistoryResponseModel instantiates a new ResourceLevelClusterBillingHistoryResponseModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResourceLevelClusterBillingHistoryResponseModel() *ResourceLevelClusterBillingHistoryResponseModel {
	this := ResourceLevelClusterBillingHistoryResponseModel{}
	return &this
}

// NewResourceLevelClusterBillingHistoryResponseModelWithDefaults instantiates a new ResourceLevelClusterBillingHistoryResponseModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResourceLevelClusterBillingHistoryResponseModelWithDefaults() *ResourceLevelClusterBillingHistoryResponseModel {
	this := ResourceLevelClusterBillingHistoryResponseModel{}
	return &this
}

// GetBillingHistoryCluster returns the BillingHistoryCluster field value if set, zero value otherwise.
func (o *ResourceLevelClusterBillingHistoryResponseModel) GetBillingHistoryCluster() ResourceLevelBillingHistory {
	if o == nil || IsNil(o.BillingHistoryCluster) {
		var ret ResourceLevelBillingHistory
		return ret
	}
	return *o.BillingHistoryCluster
}

// GetBillingHistoryClusterOk returns a tuple with the BillingHistoryCluster field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceLevelClusterBillingHistoryResponseModel) GetBillingHistoryClusterOk() (*ResourceLevelBillingHistory, bool) {
	if o == nil || IsNil(o.BillingHistoryCluster) {
		return nil, false
	}
	return o.BillingHistoryCluster, true
}

// HasBillingHistoryCluster returns a boolean if a field has been set.
func (o *ResourceLevelClusterBillingHistoryResponseModel) HasBillingHistoryCluster() bool {
	if o != nil && !IsNil(o.BillingHistoryCluster) {
		return true
	}

	return false
}

// SetBillingHistoryCluster gets a reference to the given ResourceLevelBillingHistory and assigns it to the BillingHistoryCluster field.
func (o *ResourceLevelClusterBillingHistoryResponseModel) SetBillingHistoryCluster(v ResourceLevelBillingHistory) {
	o.BillingHistoryCluster = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ResourceLevelClusterBillingHistoryResponseModel) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceLevelClusterBillingHistoryResponseModel) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ResourceLevelClusterBillingHistoryResponseModel) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ResourceLevelClusterBillingHistoryResponseModel) SetMessage(v string) {
	o.Message = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ResourceLevelClusterBillingHistoryResponseModel) GetStatus() bool {
	if o == nil || IsNil(o.Status) {
		var ret bool
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceLevelClusterBillingHistoryResponseModel) GetStatusOk() (*bool, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ResourceLevelClusterBillingHistoryResponseModel) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given bool and assigns it to the Status field.
func (o *ResourceLevelClusterBillingHistoryResponseModel) SetStatus(v bool) {
	o.Status = &v
}

func (o ResourceLevelClusterBillingHistoryResponseModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResourceLevelClusterBillingHistoryResponseModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BillingHistoryCluster) {
		toSerialize["billing_history_cluster"] = o.BillingHistoryCluster
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableResourceLevelClusterBillingHistoryResponseModel struct {
	value *ResourceLevelClusterBillingHistoryResponseModel
	isSet bool
}

func (v NullableResourceLevelClusterBillingHistoryResponseModel) Get() *ResourceLevelClusterBillingHistoryResponseModel {
	return v.value
}

func (v *NullableResourceLevelClusterBillingHistoryResponseModel) Set(val *ResourceLevelClusterBillingHistoryResponseModel) {
	v.value = val
	v.isSet = true
}

func (v NullableResourceLevelClusterBillingHistoryResponseModel) IsSet() bool {
	return v.isSet
}

func (v *NullableResourceLevelClusterBillingHistoryResponseModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourceLevelClusterBillingHistoryResponseModel(val *ResourceLevelClusterBillingHistoryResponseModel) *NullableResourceLevelClusterBillingHistoryResponseModel {
	return &NullableResourceLevelClusterBillingHistoryResponseModel{value: val, isSet: true}
}

func (v NullableResourceLevelClusterBillingHistoryResponseModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourceLevelClusterBillingHistoryResponseModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
