/*
Infrahub-API

Leverage the Infrahub API and Hyperstack platform to easily create, manage, and scale powerful GPU virtual machines and their associated resources.   Access this SDK to automate the deployment of your workloads and streamline your infrastructure management.  To contribute, please raise an issue with a bug report, feature request, feedback, or general inquiry.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hyperstack

import (
	"encoding/json"
)

// checks if the SecurityRulesFieldsForInstance type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SecurityRulesFieldsForInstance{}

// SecurityRulesFieldsForInstance struct for SecurityRulesFieldsForInstance
type SecurityRulesFieldsForInstance struct {
	CreatedAt      *CustomTime `json:"created_at,omitempty"`
	Direction      *string     `json:"direction,omitempty"`
	Ethertype      *string     `json:"ethertype,omitempty"`
	Id             *int32      `json:"id,omitempty"`
	PortRangeMax   *int32      `json:"port_range_max,omitempty"`
	PortRangeMin   *int32      `json:"port_range_min,omitempty"`
	Protocol       *string     `json:"protocol,omitempty"`
	RemoteIpPrefix *string     `json:"remote_ip_prefix,omitempty"`
	Status         *string     `json:"status,omitempty"`
}

// NewSecurityRulesFieldsForInstance instantiates a new SecurityRulesFieldsForInstance object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecurityRulesFieldsForInstance() *SecurityRulesFieldsForInstance {
	this := SecurityRulesFieldsForInstance{}
	return &this
}

// NewSecurityRulesFieldsForInstanceWithDefaults instantiates a new SecurityRulesFieldsForInstance object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecurityRulesFieldsForInstanceWithDefaults() *SecurityRulesFieldsForInstance {
	this := SecurityRulesFieldsForInstance{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *SecurityRulesFieldsForInstance) GetCreatedAt() CustomTime {
	if o == nil || IsNil(o.CreatedAt) {
		var ret CustomTime
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecurityRulesFieldsForInstance) GetCreatedAtOk() (*CustomTime, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *SecurityRulesFieldsForInstance) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given CustomTime and assigns it to the CreatedAt field.
func (o *SecurityRulesFieldsForInstance) SetCreatedAt(v CustomTime) {
	o.CreatedAt = &v
}

// GetDirection returns the Direction field value if set, zero value otherwise.
func (o *SecurityRulesFieldsForInstance) GetDirection() string {
	if o == nil || IsNil(o.Direction) {
		var ret string
		return ret
	}
	return *o.Direction
}

// GetDirectionOk returns a tuple with the Direction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecurityRulesFieldsForInstance) GetDirectionOk() (*string, bool) {
	if o == nil || IsNil(o.Direction) {
		return nil, false
	}
	return o.Direction, true
}

// HasDirection returns a boolean if a field has been set.
func (o *SecurityRulesFieldsForInstance) HasDirection() bool {
	if o != nil && !IsNil(o.Direction) {
		return true
	}

	return false
}

// SetDirection gets a reference to the given string and assigns it to the Direction field.
func (o *SecurityRulesFieldsForInstance) SetDirection(v string) {
	o.Direction = &v
}

// GetEthertype returns the Ethertype field value if set, zero value otherwise.
func (o *SecurityRulesFieldsForInstance) GetEthertype() string {
	if o == nil || IsNil(o.Ethertype) {
		var ret string
		return ret
	}
	return *o.Ethertype
}

// GetEthertypeOk returns a tuple with the Ethertype field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecurityRulesFieldsForInstance) GetEthertypeOk() (*string, bool) {
	if o == nil || IsNil(o.Ethertype) {
		return nil, false
	}
	return o.Ethertype, true
}

// HasEthertype returns a boolean if a field has been set.
func (o *SecurityRulesFieldsForInstance) HasEthertype() bool {
	if o != nil && !IsNil(o.Ethertype) {
		return true
	}

	return false
}

// SetEthertype gets a reference to the given string and assigns it to the Ethertype field.
func (o *SecurityRulesFieldsForInstance) SetEthertype(v string) {
	o.Ethertype = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *SecurityRulesFieldsForInstance) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecurityRulesFieldsForInstance) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *SecurityRulesFieldsForInstance) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *SecurityRulesFieldsForInstance) SetId(v int32) {
	o.Id = &v
}

// GetPortRangeMax returns the PortRangeMax field value if set, zero value otherwise.
func (o *SecurityRulesFieldsForInstance) GetPortRangeMax() int32 {
	if o == nil || IsNil(o.PortRangeMax) {
		var ret int32
		return ret
	}
	return *o.PortRangeMax
}

// GetPortRangeMaxOk returns a tuple with the PortRangeMax field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecurityRulesFieldsForInstance) GetPortRangeMaxOk() (*int32, bool) {
	if o == nil || IsNil(o.PortRangeMax) {
		return nil, false
	}
	return o.PortRangeMax, true
}

// HasPortRangeMax returns a boolean if a field has been set.
func (o *SecurityRulesFieldsForInstance) HasPortRangeMax() bool {
	if o != nil && !IsNil(o.PortRangeMax) {
		return true
	}

	return false
}

// SetPortRangeMax gets a reference to the given int32 and assigns it to the PortRangeMax field.
func (o *SecurityRulesFieldsForInstance) SetPortRangeMax(v int32) {
	o.PortRangeMax = &v
}

// GetPortRangeMin returns the PortRangeMin field value if set, zero value otherwise.
func (o *SecurityRulesFieldsForInstance) GetPortRangeMin() int32 {
	if o == nil || IsNil(o.PortRangeMin) {
		var ret int32
		return ret
	}
	return *o.PortRangeMin
}

// GetPortRangeMinOk returns a tuple with the PortRangeMin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecurityRulesFieldsForInstance) GetPortRangeMinOk() (*int32, bool) {
	if o == nil || IsNil(o.PortRangeMin) {
		return nil, false
	}
	return o.PortRangeMin, true
}

// HasPortRangeMin returns a boolean if a field has been set.
func (o *SecurityRulesFieldsForInstance) HasPortRangeMin() bool {
	if o != nil && !IsNil(o.PortRangeMin) {
		return true
	}

	return false
}

// SetPortRangeMin gets a reference to the given int32 and assigns it to the PortRangeMin field.
func (o *SecurityRulesFieldsForInstance) SetPortRangeMin(v int32) {
	o.PortRangeMin = &v
}

// GetProtocol returns the Protocol field value if set, zero value otherwise.
func (o *SecurityRulesFieldsForInstance) GetProtocol() string {
	if o == nil || IsNil(o.Protocol) {
		var ret string
		return ret
	}
	return *o.Protocol
}

// GetProtocolOk returns a tuple with the Protocol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecurityRulesFieldsForInstance) GetProtocolOk() (*string, bool) {
	if o == nil || IsNil(o.Protocol) {
		return nil, false
	}
	return o.Protocol, true
}

// HasProtocol returns a boolean if a field has been set.
func (o *SecurityRulesFieldsForInstance) HasProtocol() bool {
	if o != nil && !IsNil(o.Protocol) {
		return true
	}

	return false
}

// SetProtocol gets a reference to the given string and assigns it to the Protocol field.
func (o *SecurityRulesFieldsForInstance) SetProtocol(v string) {
	o.Protocol = &v
}

// GetRemoteIpPrefix returns the RemoteIpPrefix field value if set, zero value otherwise.
func (o *SecurityRulesFieldsForInstance) GetRemoteIpPrefix() string {
	if o == nil || IsNil(o.RemoteIpPrefix) {
		var ret string
		return ret
	}
	return *o.RemoteIpPrefix
}

// GetRemoteIpPrefixOk returns a tuple with the RemoteIpPrefix field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecurityRulesFieldsForInstance) GetRemoteIpPrefixOk() (*string, bool) {
	if o == nil || IsNil(o.RemoteIpPrefix) {
		return nil, false
	}
	return o.RemoteIpPrefix, true
}

// HasRemoteIpPrefix returns a boolean if a field has been set.
func (o *SecurityRulesFieldsForInstance) HasRemoteIpPrefix() bool {
	if o != nil && !IsNil(o.RemoteIpPrefix) {
		return true
	}

	return false
}

// SetRemoteIpPrefix gets a reference to the given string and assigns it to the RemoteIpPrefix field.
func (o *SecurityRulesFieldsForInstance) SetRemoteIpPrefix(v string) {
	o.RemoteIpPrefix = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *SecurityRulesFieldsForInstance) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecurityRulesFieldsForInstance) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *SecurityRulesFieldsForInstance) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *SecurityRulesFieldsForInstance) SetStatus(v string) {
	o.Status = &v
}

func (o SecurityRulesFieldsForInstance) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SecurityRulesFieldsForInstance) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.Direction) {
		toSerialize["direction"] = o.Direction
	}
	if !IsNil(o.Ethertype) {
		toSerialize["ethertype"] = o.Ethertype
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.PortRangeMax) {
		toSerialize["port_range_max"] = o.PortRangeMax
	}
	if !IsNil(o.PortRangeMin) {
		toSerialize["port_range_min"] = o.PortRangeMin
	}
	if !IsNil(o.Protocol) {
		toSerialize["protocol"] = o.Protocol
	}
	if !IsNil(o.RemoteIpPrefix) {
		toSerialize["remote_ip_prefix"] = o.RemoteIpPrefix
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableSecurityRulesFieldsForInstance struct {
	value *SecurityRulesFieldsForInstance
	isSet bool
}

func (v NullableSecurityRulesFieldsForInstance) Get() *SecurityRulesFieldsForInstance {
	return v.value
}

func (v *NullableSecurityRulesFieldsForInstance) Set(val *SecurityRulesFieldsForInstance) {
	v.value = val
	v.isSet = true
}

func (v NullableSecurityRulesFieldsForInstance) IsSet() bool {
	return v.isSet
}

func (v *NullableSecurityRulesFieldsForInstance) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecurityRulesFieldsForInstance(val *SecurityRulesFieldsForInstance) *NullableSecurityRulesFieldsForInstance {
	return &NullableSecurityRulesFieldsForInstance{value: val, isSet: true}
}

func (v NullableSecurityRulesFieldsForInstance) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecurityRulesFieldsForInstance) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
