/*
Infrahub-API

Leverage the Infrahub API and Hyperstack platform to easily create, manage, and scale powerful GPU virtual machines and their associated resources.   Access this SDK to automate the deployment of your workloads and streamline your infrastructure management.  To contribute, please raise an issue with a bug report, feature request, feedback, or general inquiry.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hyperstack

import (
	"encoding/json"
)

// checks if the AttachCallbackResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AttachCallbackResponse{}

// AttachCallbackResponse struct for AttachCallbackResponse
type AttachCallbackResponse struct {
	Message *string `json:"message,omitempty"`
	Status  *bool   `json:"status,omitempty"`
	Url     *string `json:"url,omitempty"`
}

// NewAttachCallbackResponse instantiates a new AttachCallbackResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAttachCallbackResponse() *AttachCallbackResponse {
	this := AttachCallbackResponse{}
	return &this
}

// NewAttachCallbackResponseWithDefaults instantiates a new AttachCallbackResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAttachCallbackResponseWithDefaults() *AttachCallbackResponse {
	this := AttachCallbackResponse{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *AttachCallbackResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AttachCallbackResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *AttachCallbackResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *AttachCallbackResponse) SetMessage(v string) {
	o.Message = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *AttachCallbackResponse) GetStatus() bool {
	if o == nil || IsNil(o.Status) {
		var ret bool
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AttachCallbackResponse) GetStatusOk() (*bool, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *AttachCallbackResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given bool and assigns it to the Status field.
func (o *AttachCallbackResponse) SetStatus(v bool) {
	o.Status = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *AttachCallbackResponse) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AttachCallbackResponse) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *AttachCallbackResponse) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *AttachCallbackResponse) SetUrl(v string) {
	o.Url = &v
}

func (o AttachCallbackResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AttachCallbackResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	return toSerialize, nil
}

type NullableAttachCallbackResponse struct {
	value *AttachCallbackResponse
	isSet bool
}

func (v NullableAttachCallbackResponse) Get() *AttachCallbackResponse {
	return v.value
}

func (v *NullableAttachCallbackResponse) Set(val *AttachCallbackResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAttachCallbackResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAttachCallbackResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAttachCallbackResponse(val *AttachCallbackResponse) *NullableAttachCallbackResponse {
	return &NullableAttachCallbackResponse{value: val, isSet: true}
}

func (v NullableAttachCallbackResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAttachCallbackResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
