version: '3'

silent: true

vars:
  DIR_ARTIFACTS: "{{.ROOT_DIR}}/artifacts"
  DIR_DATA: "{{.ROOT_DIR}}/data"
  API_JSON_PATH: "{{.DIR_ARTIFACTS}}/api.json"
  LIB_DIR: "lib"
  DIR_PACKAGE: "{{.ROOT_DIR}}/{{.LIB_DIR}}"

env:
  HYPERSTACK_STAGING: "true"
  HYPERSTACK_API_KEY: ~

tasks:
  init:
    desc: |
      Install all the necessary dependencies
    vars:
      DEPS: |-
        github.com/deepmap/oapi-codegen/cmd/oapi-codegen
    cmds:
      # language=bash
      - |
        # TODO: check go.mod
        # go install
        go get {{.DEPS}}
        go install {{.DEPS}}

  pull-api:
    desc: |
      Pulls the latest api.json from the server
    vars:
      SPEC_PATH: |-
        https://infrahub-api-doc.nexgencloud.com/api.json
    cmds:
      # language=bash
      - |
        echo "Pulling the latest swagger spec and generating Go SDK..."
        curl "{{.SPEC_PATH}}"  | \
          python3 -c "import sys, urllib.parse; print(urllib.parse.unquote(sys.stdin.read()))" \
            > "{{.API_JSON_PATH}}"
        sed -i 's/Update Keypair name response/UpdatedKeypairNameResponseAPIObject/g' "{{.API_JSON_PATH}}"
        sed -i 's/Import Keypair Response/ImportedKeypairResponseAPIObject/g' "{{.API_JSON_PATH}}"

  build:
    desc: |
      Generates go sdk file from api.json
    vars:
      SPEC_PATH: |-
        https://infrahub-api-doc.nexgencloud.com/api.json
      # TODO: from go.mod
      PROJECT: "github.com\\/NexGenCloud\\/hyperstack-sdk-go"
      TIME_PACKAGE: "time"
    env:
      DIR_ARTIFACTS: "{{.DIR_ARTIFACTS}}"
      DIR_PACKAGE: "{{.DIR_PACKAGE}}"
    cmds:
      # language=bash
      - |
        echo -n "Generating Go SDK... "
        go run sdk_generator.go
        mkdir -p "{{.DIR_PACKAGE}}/{{.TIME_PACKAGE}}"
        find "{{.DIR_PACKAGE}}" \
          -name "*.go" \
          -exec sed -i -e "s/*time.Time/*{{.TIME_PACKAGE}}.CustomTime/g" {} \;
        find "{{.DIR_PACKAGE}}" \
          -name "*.go" \
          -exec sed -i -e 's/"time"/"{{.PROJECT}}\/{{.LIB_DIR}}\/{{.TIME_PACKAGE}}"/g' {} \;
        sed 's/PACKAGE_REPLACE/{{.TIME_PACKAGE}}/g' "{{.DIR_DATA}}/CustomTime.go" \
          > "{{.DIR_PACKAGE}}/{{.TIME_PACKAGE}}/CustomTime.go"
        echo "done"

  test:
    desc: |
      Runs tests
    env:
      DIR_ARTIFACTS: "{{.DIR_ARTIFACTS}}"
    cmds:
      # language=bash
      - go test -v sdk_generator_test.go
