// Package user_consent provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.2.0 DO NOT EDIT.
package user_consent

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// Defines values for ConsentBlockType.
const (
	Failure ConsentBlockType = "failure"
	Info    ConsentBlockType = "info"
	Success ConsentBlockType = "success"
	Text    ConsentBlockType = "text"
	Warning ConsentBlockType = "warning"
)

// Defines values for RecordConsentRequestAction.
const (
	RecordConsentRequestActionGranted RecordConsentRequestAction = "granted"
	RecordConsentRequestActionRevoked RecordConsentRequestAction = "revoked"
)

// Defines values for RecordConsentRequestConsentMethod.
const (
	RecordConsentRequestConsentMethodAdminOverride RecordConsentRequestConsentMethod = "admin_override"
	RecordConsentRequestConsentMethodApi           RecordConsentRequestConsentMethod = "api"
	RecordConsentRequestConsentMethodWebCheckbox   RecordConsentRequestConsentMethod = "web_checkbox"
)

// Defines values for RecordConsentRequestConsentType.
const (
	AutoTopUp RecordConsentRequestConsentType = "auto_top_up"
)

// Defines values for UpdateConsentRequestAction.
const (
	UpdateConsentRequestActionGranted UpdateConsentRequestAction = "granted"
	UpdateConsentRequestActionRevoked UpdateConsentRequestAction = "revoked"
)

// Defines values for UpdateConsentRequestConsentMethod.
const (
	UpdateConsentRequestConsentMethodAdminOverride UpdateConsentRequestConsentMethod = "admin_override"
	UpdateConsentRequestConsentMethodApi           UpdateConsentRequestConsentMethod = "api"
	UpdateConsentRequestConsentMethodWebCheckbox   UpdateConsentRequestConsentMethod = "web_checkbox"
)

// ConsentActionResponse defines model for ConsentActionResponse.
type ConsentActionResponse struct {
	Consent *UserConsent `json:"consent,omitempty"`
	Message *string      `json:"message,omitempty"`
}

// ConsentBlock defines model for ConsentBlock.
type ConsentBlock struct {
	// Text Block text, may contain ${variable} placeholders
	Text *string `json:"text,omitempty"`

	// Type Block display type
	Type *ConsentBlockType `json:"type,omitempty"`
}

// ConsentBlockType Block display type
type ConsentBlockType string

// ConsentTemplate defines model for ConsentTemplate.
type ConsentTemplate struct {
	Blocks *[]ConsentBlock `json:"blocks,omitempty"`

	// Version Template version identifier
	Version *string `json:"version,omitempty"`
}

// ConsentTemplatesResponse defines model for ConsentTemplatesResponse.
type ConsentTemplatesResponse struct {
	// Templates Templates keyed by consent type
	Templates *map[string]interface{} `json:"templates,omitempty"`
}

// ErrorResponseModel defines model for ErrorResponseModel.
type ErrorResponseModel struct {
	ErrorReason *string `json:"error_reason,omitempty"`
	Message     *string `json:"message,omitempty"`
	Status      *bool   `json:"status,omitempty"`
}

// RecordConsentRequest defines model for RecordConsentRequest.
type RecordConsentRequest struct {
	Action        RecordConsentRequestAction         `json:"action"`
	ConsentMethod *RecordConsentRequestConsentMethod `json:"consent_method,omitempty"`
	ConsentType   RecordConsentRequestConsentType    `json:"consent_type"`

	// ConsentVersion Version identifier. Defaults to the current version for the consent type
	ConsentVersion *string `json:"consent_version,omitempty"`

	// Metadata Consent-type-specific metadata
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
}

// RecordConsentRequestAction defines model for RecordConsentRequest.Action.
type RecordConsentRequestAction string

// RecordConsentRequestConsentMethod defines model for RecordConsentRequest.ConsentMethod.
type RecordConsentRequestConsentMethod string

// RecordConsentRequestConsentType defines model for RecordConsentRequest.ConsentType.
type RecordConsentRequestConsentType string

// UpdateConsentRequest defines model for UpdateConsentRequest.
type UpdateConsentRequest struct {
	Action        UpdateConsentRequestAction         `json:"action"`
	ConsentMethod *UpdateConsentRequestConsentMethod `json:"consent_method,omitempty"`

	// ConsentVersion Version identifier. Defaults to the current version for the consent type
	ConsentVersion *string `json:"consent_version,omitempty"`

	// Metadata Consent-type-specific metadata
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
}

// UpdateConsentRequestAction defines model for UpdateConsentRequest.Action.
type UpdateConsentRequestAction string

// UpdateConsentRequestConsentMethod defines model for UpdateConsentRequest.ConsentMethod.
type UpdateConsentRequestConsentMethod string

// UserConsent defines model for UserConsent.
type UserConsent struct {
	Action        *string `json:"action,omitempty"`
	ConsentMethod *string `json:"consent_method,omitempty"`
	ConsentType   *string `json:"consent_type,omitempty"`
	CreatedAt     *string `json:"created_at,omitempty"`
	Id            *int    `json:"id,omitempty"`
	IpAddress     *string `json:"ip_address,omitempty"`
	OrgId         *int    `json:"org_id,omitempty"`
	UpdatedAt     *string `json:"updated_at,omitempty"`
	UserId        *int    `json:"user_id,omitempty"`
}

// UserConsentsResponse defines model for UserConsentsResponse.
type UserConsentsResponse struct {
	Consents *[]UserConsent `json:"consents,omitempty"`
}

// GetAllConsentsForAUserParams defines parameters for GetAllConsentsForAUser.
type GetAllConsentsForAUserParams struct {
	ConsentType *string `form:"consent_type,omitempty" json:"consent_type,omitempty"`
}

// AddANewConsentForAUserJSONRequestBody defines body for AddANewConsentForAUser for application/json ContentType.
type AddANewConsentForAUserJSONRequestBody = RecordConsentRequest

// UpdateAConsentActionByTypeJSONRequestBody defines body for UpdateAConsentActionByType for application/json ContentType.
type UpdateAConsentActionByTypeJSONRequestBody = UpdateConsentRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetAllConsentsForAUser request
	GetAllConsentsForAUser(ctx context.Context, params *GetAllConsentsForAUserParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AddANewConsentForAUserWithBody request with any body
	AddANewConsentForAUserWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	AddANewConsentForAUser(ctx context.Context, body AddANewConsentForAUserJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAllConsentTemplates request
	GetAllConsentTemplates(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetConsentTemplateByType request
	GetConsentTemplateByType(ctx context.Context, consentType string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateAConsentActionByTypeWithBody request with any body
	UpdateAConsentActionByTypeWithBody(ctx context.Context, consentType string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateAConsentActionByType(ctx context.Context, consentType string, body UpdateAConsentActionByTypeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetAllConsentsForAUser(ctx context.Context, params *GetAllConsentsForAUserParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAllConsentsForAUserRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AddANewConsentForAUserWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAddANewConsentForAUserRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AddANewConsentForAUser(ctx context.Context, body AddANewConsentForAUserJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAddANewConsentForAUserRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetAllConsentTemplates(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAllConsentTemplatesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetConsentTemplateByType(ctx context.Context, consentType string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetConsentTemplateByTypeRequest(c.Server, consentType)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateAConsentActionByTypeWithBody(ctx context.Context, consentType string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateAConsentActionByTypeRequestWithBody(c.Server, consentType, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateAConsentActionByType(ctx context.Context, consentType string, body UpdateAConsentActionByTypeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateAConsentActionByTypeRequest(c.Server, consentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetAllConsentsForAUserRequest generates requests for GetAllConsentsForAUser
func NewGetAllConsentsForAUserRequest(server string, params *GetAllConsentsForAUserParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/auth/user-consent")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.ConsentType != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "consent_type", runtime.ParamLocationQuery, *params.ConsentType); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewAddANewConsentForAUserRequest calls the generic AddANewConsentForAUser builder with application/json body
func NewAddANewConsentForAUserRequest(server string, body AddANewConsentForAUserJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewAddANewConsentForAUserRequestWithBody(server, "application/json", bodyReader)
}

// NewAddANewConsentForAUserRequestWithBody generates requests for AddANewConsentForAUser with any type of body
func NewAddANewConsentForAUserRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/auth/user-consent")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetAllConsentTemplatesRequest generates requests for GetAllConsentTemplates
func NewGetAllConsentTemplatesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/auth/user-consent/templates")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetConsentTemplateByTypeRequest generates requests for GetConsentTemplateByType
func NewGetConsentTemplateByTypeRequest(server string, consentType string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "consent_type", runtime.ParamLocationPath, consentType)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/auth/user-consent/templates/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdateAConsentActionByTypeRequest calls the generic UpdateAConsentActionByType builder with application/json body
func NewUpdateAConsentActionByTypeRequest(server string, consentType string, body UpdateAConsentActionByTypeJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateAConsentActionByTypeRequestWithBody(server, consentType, "application/json", bodyReader)
}

// NewUpdateAConsentActionByTypeRequestWithBody generates requests for UpdateAConsentActionByType with any type of body
func NewUpdateAConsentActionByTypeRequestWithBody(server string, consentType string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "consent_type", runtime.ParamLocationPath, consentType)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/auth/user-consent/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetAllConsentsForAUserWithResponse request
	GetAllConsentsForAUserWithResponse(ctx context.Context, params *GetAllConsentsForAUserParams, reqEditors ...RequestEditorFn) (*GetAllConsentsForAUserResponse, error)

	// AddANewConsentForAUserWithBodyWithResponse request with any body
	AddANewConsentForAUserWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AddANewConsentForAUserResponse, error)

	AddANewConsentForAUserWithResponse(ctx context.Context, body AddANewConsentForAUserJSONRequestBody, reqEditors ...RequestEditorFn) (*AddANewConsentForAUserResponse, error)

	// GetAllConsentTemplatesWithResponse request
	GetAllConsentTemplatesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetAllConsentTemplatesResponse, error)

	// GetConsentTemplateByTypeWithResponse request
	GetConsentTemplateByTypeWithResponse(ctx context.Context, consentType string, reqEditors ...RequestEditorFn) (*GetConsentTemplateByTypeResponse, error)

	// UpdateAConsentActionByTypeWithBodyWithResponse request with any body
	UpdateAConsentActionByTypeWithBodyWithResponse(ctx context.Context, consentType string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateAConsentActionByTypeResponse, error)

	UpdateAConsentActionByTypeWithResponse(ctx context.Context, consentType string, body UpdateAConsentActionByTypeJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateAConsentActionByTypeResponse, error)
}

type GetAllConsentsForAUserResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *UserConsentsResponse
	JSON400      *ErrorResponseModel
	JSON404      *ErrorResponseModel
}

// Status returns HTTPResponse.Status
func (r GetAllConsentsForAUserResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAllConsentsForAUserResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type AddANewConsentForAUserResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ConsentActionResponse
	JSON400      *ErrorResponseModel
	JSON404      *ErrorResponseModel
}

// Status returns HTTPResponse.Status
func (r AddANewConsentForAUserResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AddANewConsentForAUserResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetAllConsentTemplatesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ConsentTemplatesResponse
	JSON401      *ErrorResponseModel
}

// Status returns HTTPResponse.Status
func (r GetAllConsentTemplatesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAllConsentTemplatesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetConsentTemplateByTypeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ConsentTemplate
	JSON400      *ErrorResponseModel
	JSON401      *ErrorResponseModel
	JSON404      *ErrorResponseModel
}

// Status returns HTTPResponse.Status
func (r GetConsentTemplateByTypeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetConsentTemplateByTypeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UpdateAConsentActionByTypeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ConsentActionResponse
	JSON400      *ErrorResponseModel
	JSON404      *ErrorResponseModel
}

// Status returns HTTPResponse.Status
func (r UpdateAConsentActionByTypeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateAConsentActionByTypeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetAllConsentsForAUserWithResponse request returning *GetAllConsentsForAUserResponse
func (c *ClientWithResponses) GetAllConsentsForAUserWithResponse(ctx context.Context, params *GetAllConsentsForAUserParams, reqEditors ...RequestEditorFn) (*GetAllConsentsForAUserResponse, error) {
	rsp, err := c.GetAllConsentsForAUser(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAllConsentsForAUserResponse(rsp)
}

// AddANewConsentForAUserWithBodyWithResponse request with arbitrary body returning *AddANewConsentForAUserResponse
func (c *ClientWithResponses) AddANewConsentForAUserWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AddANewConsentForAUserResponse, error) {
	rsp, err := c.AddANewConsentForAUserWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAddANewConsentForAUserResponse(rsp)
}

func (c *ClientWithResponses) AddANewConsentForAUserWithResponse(ctx context.Context, body AddANewConsentForAUserJSONRequestBody, reqEditors ...RequestEditorFn) (*AddANewConsentForAUserResponse, error) {
	rsp, err := c.AddANewConsentForAUser(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAddANewConsentForAUserResponse(rsp)
}

// GetAllConsentTemplatesWithResponse request returning *GetAllConsentTemplatesResponse
func (c *ClientWithResponses) GetAllConsentTemplatesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetAllConsentTemplatesResponse, error) {
	rsp, err := c.GetAllConsentTemplates(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAllConsentTemplatesResponse(rsp)
}

// GetConsentTemplateByTypeWithResponse request returning *GetConsentTemplateByTypeResponse
func (c *ClientWithResponses) GetConsentTemplateByTypeWithResponse(ctx context.Context, consentType string, reqEditors ...RequestEditorFn) (*GetConsentTemplateByTypeResponse, error) {
	rsp, err := c.GetConsentTemplateByType(ctx, consentType, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetConsentTemplateByTypeResponse(rsp)
}

// UpdateAConsentActionByTypeWithBodyWithResponse request with arbitrary body returning *UpdateAConsentActionByTypeResponse
func (c *ClientWithResponses) UpdateAConsentActionByTypeWithBodyWithResponse(ctx context.Context, consentType string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateAConsentActionByTypeResponse, error) {
	rsp, err := c.UpdateAConsentActionByTypeWithBody(ctx, consentType, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateAConsentActionByTypeResponse(rsp)
}

func (c *ClientWithResponses) UpdateAConsentActionByTypeWithResponse(ctx context.Context, consentType string, body UpdateAConsentActionByTypeJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateAConsentActionByTypeResponse, error) {
	rsp, err := c.UpdateAConsentActionByType(ctx, consentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateAConsentActionByTypeResponse(rsp)
}

// ParseGetAllConsentsForAUserResponse parses an HTTP response from a GetAllConsentsForAUserWithResponse call
func ParseGetAllConsentsForAUserResponse(rsp *http.Response) (*GetAllConsentsForAUserResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAllConsentsForAUserResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest UserConsentsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponseModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponseModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseAddANewConsentForAUserResponse parses an HTTP response from a AddANewConsentForAUserWithResponse call
func ParseAddANewConsentForAUserResponse(rsp *http.Response) (*AddANewConsentForAUserResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AddANewConsentForAUserResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ConsentActionResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponseModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponseModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGetAllConsentTemplatesResponse parses an HTTP response from a GetAllConsentTemplatesWithResponse call
func ParseGetAllConsentTemplatesResponse(rsp *http.Response) (*GetAllConsentTemplatesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAllConsentTemplatesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ConsentTemplatesResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponseModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseGetConsentTemplateByTypeResponse parses an HTTP response from a GetConsentTemplateByTypeWithResponse call
func ParseGetConsentTemplateByTypeResponse(rsp *http.Response) (*GetConsentTemplateByTypeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetConsentTemplateByTypeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ConsentTemplate
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponseModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponseModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponseModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseUpdateAConsentActionByTypeResponse parses an HTTP response from a UpdateAConsentActionByTypeWithResponse call
func ParseUpdateAConsentActionByTypeResponse(rsp *http.Response) (*UpdateAConsentActionByTypeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateAConsentActionByTypeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ConsentActionResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponseModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponseModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}
