name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Jobs build
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    # Set up Go
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21

    # Get dependencies
    - name: Get dependencies
      run: make init
      
    # Pull latest spec
    - name: Pull latest spec
      run: make pull-api

    # Generate SDK
    - name: Generate SDK
      run: make build

    # Run tests 
    - name: Run tests
      run: make test
