name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Jobs build
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Install Task
      uses: arduino/setup-task@v2

    - name: Get dependencies
      run: task init
      
    - name: Pull latest spec
      run: task pull-api

    - name: Generate SDK
      run: task build

    - name: Run tests
      run: task test
